[package]
name = "rbj-eq"
version = "0.4.0"
edition = "2021"
authors = ["Bart Massey <bart.massey@gmail.com>"]
description = 'Robert Bristow-Johnson "equalizer filters"'
license = "MIT"
repository = "https://github.com/BartMassey/rbj-eq"
readme = "README.md"
categories = ["multimedia::audio"]

[dependencies.num-traits]
version = "0.2"
default-features = false
optional = true
features = ["libm"]

[features]
libm = ["num-traits"]
